// Generated by scripts/lidar/pack_cloud.py — do not edit by hand.
// Filenames carry a content hash, so they are safe to cache forever.
export const LIDAR_CLOUDS = {
  "manhattan-portrait": "/lidar/manhattan-portrait.e2645b1941.lpc",
  "manhattan-wide": "/lidar/manhattan-wide.ab05ce4662.lpc",
} as const;
